### PR TITLE
fix(a11y): update vertical nav selected and hover colors

### PR DESCRIPTION
**Pull request by andyfeds**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: [CDE-2115](https://jira.eng.vmware.com/browse/CDE-2115)

## What is the new behavior?
To fix the a11y defect the below changes have been made:

- Keep current unselected background colors.
- Update the selected option background to white.
- Hover and active (clicked) colors to be different from one another for light theme. Hover (construction-200). Active (construction-300)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by sandeepkulki — APPROVED** [review]

**Review by kevinbuhmann — APPROVED** [review]

**Review by valentin-mladenov — COMMENTED** [review]
I have noticed that in light theme `--clr-vertical-nav-hover-bg-color` and `--clr-vertical-nav-active-bg-color` are using the same `construction-100` color.

**Comment by andyfeds** [comment]
> I have noticed that in light theme `--clr-vertical-nav-hover-bg-color` and `--clr-vertical-nav-active-bg-color` are using the same `construction-100` color.

Yes, I see that too, will confirm this with Grigor

**Review by Jinnie — COMMENTED** [review]
Assigning global colors to `--clr-...` tokens is a bit controversial.
It requires dark-theme overrides in the component specific `_properties.vertical-nav.scss` file, which short-circuits any possibility to deliver proper theming through design tokens.
I think we should stick to using `--cds-alias-...` aliases as immediate assignment to the `--clr-...` space tokens, and not directly link to `global` colors.

**Comment by andyfeds** [comment]
The new `cds-alias` tokens for the vertical nav have to be added in `@cds/core` which involves changes to the core version.
As a temporary solution, I've added `--cds-alias-...` in the `temp-overrides.scss` file for now and mapped these to the --clr-... space tokens instead of the global variables. Let me know if you see any issues @Jinnie @valentin-mladenov

**Review by valentin-mladenov — APPROVED** [review]
LGTM

**Pull request merged**
