### PR TITLE
chore: clean up template whitespace

### PR DESCRIPTION
**Pull request by kevinbuhmann**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [N/A] Tests for the changes have been added (for bug fixes / features)
- [N/A] Docs have been added / updated (for bug fixes / features)
- [N/A] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ashleyryan** [comment]
Is this a change to the linter or prettier config?

**Comment by ashleyryan** [comment]
>No. I just cleaned up the odd whitespace formatting prettier introduced to make the HTML more readable.

Right, so manually fixing things is not going to be a longer term fix. If prettier is doing this - we need to fix the prettier config so it doesn't happen again. The next time someone edits one of these files and hits save, prettier will mangle it again.

**Comment by kevinbuhmann** [comment]
Prettier won't mangle these changes.

**Comment by kevinbuhmann** [comment]
Prettier preserves existing whitespace which 1) mangles tags when adding newlines and 2) keeps unnecessary whitespace when removing newlines. The commits in this PR changes insignificant whitespace and `prettier` will respect that.

**Review by Jinnie — APPROVED** [review]
Please backport to supported version branches too, or we may have troubles cherrypicking and merging future backports in these files.

**Review by ashleyryan — APPROVED** [review]

**Comment by kevinbuhmann** [comment]
> Please backport to supported version branches too, or we may have troubles cherrypicking and merging future backports in these files.

This is backported in #161.

**Pull request merged**
