### PR TITLE
fix(accordion): style disabled panel button correctly

### PR DESCRIPTION
**Pull request by kevinbuhmann**
CD-247

### CODE REVIEW

**Comment by dtsanevmw** [comment]
@kevinbuhmann Shouldn't we add the same color to the caret icon in disabled state?

**Comment by kevinbuhmann** [comment]
> Shouldn't we add the same color to the caret icon in disabled state?

The caret icon color isn't changed in Clarity Core for disabled accordion panels, so I don't think so.

**Comment by colinreedmiller** [comment]
> @kevinbuhmann Shouldn't we add the same color to the caret icon in disabled state?

You can get a decision on such questions quickly by asking design to specify the correct color. Please add a member of the design team as a reviewer on this ticket.

**Review by Jinnie — APPROVED** [review]

**Comment by williamernest** [comment]
Matching the Core styles is sufficient for this task and keeps the scope aligned with the intent. If we decide that the disabled styling should also apply to the icon, we can file a followup ticket to address that in both libraries simultaneously.

**Comment by kevinbuhmann** [comment]
I still confirmation from design on my text color choices for ng-light and ng-dark.

**Comment by Jinnie** [comment]
As Will said the parity with Core should be enough. I don't want this task to creep into the next iteration. If design has some comments, we can add them iteratively.
I will merge this so we can finalize the iteration.

**Pull request merged**
