### PR TITLE
Datagrid, improve column selector button

### PR DESCRIPTION
**Pull request by Jinnie**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
Currently columns visibility is controlled in a menu triggered by a hard to understand and find button.

Issue Number: #43 

## What is the new behavior?

A button with text description is used instead

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

Visual only breaking change. No migration is needed besides updating visual regression tests, if such exist.

### CODE REVIEW

**Review by kevinbuhmann — CHANGES_REQUESTED** [review]
This looks good to me except one small thing. I think the `<span class="clr-sr-only">{{ commonStrings.keys.pickColumns }}</span>` should be removed now.

**Comment by Jinnie** [comment]
> I think the `<span class="clr-sr-only">{{ commonStrings.keys.pickColumns }}</span>` should be removed now.

Absolutely! Thanks for catching this. I thought I should not forget about it, when I started refactoring, but I did :)

**Review by kevinbuhmann — APPROVED** [review]

**Comment by Jinnie** [comment]
Thanks for the review. I'll convert it to draft, though, as it's a breaking change and we don't want to merge it yet, before v15

**Comment by kevinbuhmann** [comment]
I stripped this from the `beta` branch in favor of a new PR to merge this to `main` for 13.x.

**Pull request merged**
