### PR TITLE
fix(button): skip animation on first render of loading button

### LINKED ISSUE #1075: Buttons using a clrLoading directive have the button text faded-in on page load
## Describe the bug

Buttons using a `clrLoading` directive have the button text faded-in on page load. Buttons without the directive do not.

7B01511B-5E3E-4B61-9A50-C2B1467DACE2

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-clr16-wbbydf

1.  Observe the buttons on page load/reload

## Expected behavior

Buttons using a `clrLoading` directive should not have button text faded-in on page load.

## Versions

**Clarity version:**

- [ ] v15.x
- [x] v16.x
- [ ] Other:

**Framework version:**

Angular 16

**Device:**

- Type: PC
- OS: Windows 10
- Browser: Chrome
- Version: 119

### PR DESCRIPTION
**Pull request by kevinbuhmann**
The button text/content should only be faded when transitioning to or from a non-default state.

CDE-1596
closes #1075

## PR Checklist

- [N/A] Tests for the changes have been added (for bug fixes / features)
- [N/A] Docs have been added / updated (for bug fixes / features)
- [N/A] If applicable, have a visual design approval

## PR Type

Bugfix

## What is the current behavior?

Buttons using a `[clrLoading]` directive have the button text faded in on page load. Buttons without the directive do not.

Issue Number: #1075, CDE-1596

## What is the new behavior?

The button text/content should only be faded when transitioning to or from a non-default state.

## Does this PR introduce a breaking change?

No.

### CODE REVIEW

**Review by valentin-mladenov — COMMENTED** [review]
Is there a way to add unit or visual tests about this change?

**Review by valentin-mladenov — APPROVED** [review]
LGTM

**Comment by kevinbuhmann** [comment]
> Is there a way to add unit or visual tests about this change?

I can try.

**Comment by kevinbuhmann** [comment]
> Is there a way to add unit or visual tests about this change?

No, I don't think so.

**Pull request merged**
