### PR TITLE
deploy forked demos

### PR DESCRIPTION
**Pull request by steve-haar**
This fixes the problem of demos not being deployed when on forked branches

## PR Checklist

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by Shijir — APPROVED** [review]

**Comment by ashleyryan** [comment]
This change will run against every PR from a forked repo back to this one? Are the possibility of spam PRs an issue, using up our GitHub credits/whatever rules Netlify has?

**Comment by steve-haar** [comment]
> This change will run against every PR from a forked repo back to this one? Are the possibility of spam PRs an issue, using up our GitHub credits/whatever rules Netlify has?

The `build` GitHub workflow already runs on forked PRs. It uses the `pull_request` trigger which means it is triggered every time a pull request that is created or modified (regardless of whether it is forked or not). The problem is that workflows triggered by the `pull_request` trigger that exist on forks do not have access to GitHub secrets and therefore cannot publish the demo to netlify.

This PR simply addresses these permissions by splitting out the `pull_request` trigger into two different workflows. A `build` workflow and a `demo` workflow. The `demo` workflow runs under a `workflow_run` trigger and will have access to secrets.

So, to answer your question, this will not run on any old PRs unless they are modified. Also, this will not cause any more workflows to run.

Also, GitHub has unlimited action minutes for public repos and Netlify has unlimited deploys. Netlify does have limits on build minutes, but we don't use Netlify to build, so it doesn't come into affect.

**Comment by ashleyryan** [comment]
Ok, works for me. I thought when Matt was explaining the old build/website process he explained some sort of limit on building preview environments with PRs, which is why it caught my eye.

**Comment by steve-haar** [comment]
We used to use Netlify build minutes, which I think is what you're thinking of. We stopped using them when we did the repo split.

**Review by ashleyryan — APPROVED** [review]

**Pull request merged**
