### PR TITLE
fix(header): revert changes and align subnav to vertical nav in cds-theme

### PR DESCRIPTION
**Pull request by mivaylo**
Revert changes from #953 and align responsive nav to vertical nav.

### CODE REVIEW

**Comment by mivaylo** [comment]
This PR's changes https://github.com/vmware-clarity/ng-clarity/pull/953 have applied on the tabs (for smaller screens and hence the visual changes have not been caught, we only have tests for tabs for larger screens) because the tabs use navs under the hood.

So we want to move the changes from this PR that were done in the _nav.clarity.scss file to _responsive-nav.clarity.scss.

What this PR does is to "revert" the changes from _nav.clarity.scss file and to move all of them in their appropriate place in the _responsive-nav.clarity.scss.

The title of the file _responsive-navs.clarity.scss is maybe not appropriate because it only applies to the header-navs and the subnav navs (but not to the tabs' navs).

**Comment by mivaylo** [comment]
This is a video demo of the visual regression this PR is addressing


https://github.com/vmware-clarity/ng-clarity/assets/132376042/1458dda3-0aed-4062-a976-034b244b1ecb

**Comment by mivaylo** [comment]
Tabs in smaller screen after the change in this PR:


https://github.com/vmware-clarity/ng-clarity/assets/132376042/a69766f7-5187-4ceb-b169-9cdff260383a

**Comment by mivaylo** [comment]
Disucssed with @dtsanevmw and added some changes to revert vertical subnav to the state of v13

**Review by dtsanevmw — APPROVED** [review]

**Pull request merged**
