### PR TITLE
chore: update package-lock.json after `npm install`

### PR DESCRIPTION
**Pull request by kevinbuhmann**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [N/A] Tests for the changes have been added (for bug fixes / features)
- [N/A] Docs have been added / updated (for bug fixes / features)
- [N/A] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ashleyryan** [comment]
FWIW, I keep getting this too. I've been meaning to ask you about it - usually I delete the package.lock before committing

**Comment by steve-haar** [comment]
> FWIW, I keep getting this too. I've been meaning to ask you about it - usually I delete the package.lock before committing

Deleting package.lock will likely cause dependencies to update. We probably want to be careful doing this. I wonder if different npm versions are causing minor changes here.

**Comment by kevinbuhmann** [comment]
> Deleting package.lock will likely cause dependencies to update.

I think Ashley meant that she discards the changes.

**Comment by steve-haar** [comment]
> > Deleting package.lock will likely cause dependencies to update.
> 
> I think Ashley meant that she discards the changes.

Ah, that makes sense.

**Comment by steve-haar** [comment]
If you have changes to your lock file and you didn't update any `package.json` files, then either you have the lock file in a bad state or the last commit left the lock file in a bad state. Here is how to see which scenario you are in:

First, undo your changes to the lock file. Next, run the following: `git clean -fxd; nvm use; npm install`. If your lock file changes went away, then you just had a bad lock file somehow and all should be good. If you still see changes to your lock file after this, that means the last commit didn't properly update the lock file. In this case, ideally we would make a chore commit to update the lock file.

If this becomes an issue we can add an automated check to the CI/CD that will prevent merging a PR if the lock file is out of sync.

**Pull request closed without merging**
