### PR TITLE
fix(alert): remove space between action dropdown trigger and popup menu

### PR DESCRIPTION
**Pull request by kevinbuhmann**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [N/A] Docs have been added / updated (for bug fixes / features)
- [N/A] If applicable, have a visual design approval

## PR Type

Bugfix

## What is the current behavior?

The dropdown menu popup appears below the alert text in long alerts.

image

https://stackblitz.com/edit/uhtany?file=src%2Fapp%2Fexample.component.html

Issue Number: CDE-2066

## What is the new behavior?

The alert action dropdown menu will now appear adjacent to the trigger without any gap due to long alert content.

image

## Does this PR introduce a breaking change?

No.

## Other information

This commit fixes a regression that was introduced in 8214941015c8279051a5504c1bcbe9bd8905ab26 (#1029).

### CODE REVIEW

**Review by valentin-mladenov — APPROVED** [review]
LGTM!

Can you add `actions` dropdown for app level alerts as well?

**Comment by valentin-mladenov** [comment]
@kevinbuhmann please create a bug JIRA for this fix.

**Comment by kevinbuhmann** [comment]
> @kevinbuhmann please create a bug JIRA for this fix.

CDE-2066

**Comment by kevinbuhmann** [comment]
> Can you add `actions` dropdown for app level alerts as well?

Yeah, I can do that.

**Pull request merged**
