### PR TITLE
fix(date-picker): add null check for optional date control

### PR DESCRIPTION
**Pull request by twittwer**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

The `control` property of `ClrDateInput`'s is marked as optional and can therefore be `null`.
https://github.com/vmware-clarity/ng-clarity/blob/7cfeb3b0f53c930d56205098db14ebfb6e8b95fc/projects/angular/src/forms/datepicker/date-input.ts#L72-L74
```ts
  constructor(
    ...
    @Self()
    @Optional()
    protected control: NgControl,
    ...
  ) {
    super(viewContainerRef, ClrDateContainer, injector, control, renderer, el);
  }
```
But the `WrappedControl` which is extended by `ClrDateInput` doesn't handle nullable controls.
https://github.com/vmware-clarity/ng-clarity/blob/7cfeb3b0f53c930d56205098db14ebfb6e8b95fc/projects/angular/src/forms/common/wrapped-control.ts#L57
```ts
  constructor(
    ...
    private ngControl: NgControl,
    ...
  ) {
```

This causes ` TypeError: Cannot read properties of null (reading 'control')` when using `clrDate` and calling `markAllAsTouched` on a surrounding form.
https://github.com/vmware-clarity/ng-clarity/blob/7cfeb3b0f53c930d56205098db14ebfb6e8b95fc/projects/angular/src/forms/common/wrapped-control.ts#L146-L149
```ts
  private markAsTouched(): void {
    this.ngControl.control.markAsTouched();
    this.ngControl.control.updateValueAndValidity();
  }
```

## What is the new behavior?

The `WrappedControl` is now typed with nullable control and checks for its existence before using it.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by kevinbuhmann — APPROVED** [review]
Thanks!

**Comment by twittwer** [comment]
@kevinbuhmann How would you like to proceed with the failing test?
https://github.com/vmware-clarity/ng-clarity/blob/7cfeb3b0f53c930d56205098db14ebfb6e8b95fc/projects/angular/src/forms/datepicker/date-input.spec.ts#L109-L111

Before it tests that `NgControlService.setControl` has be called, but not with what. In reality, it was called with null what is not supported by the `NgControlService.setControl`.

Should I test the opposite and check it is not called, or remove it?

**Comment by kevinbuhmann** [comment]
We should have a test for both possibilities.

**Comment by twittwer** [comment]
I tried to add tests to the separate usage types.  
Can you have a look if it's working this way?

**Comment by twittwer** [comment]
Ok, I checked it out locally and now lint & test should succeed.

**Comment by twittwer** [comment]
I hope running `public-api:update` fixes the pipeline

**Comment by kevinbuhmann** [comment]
> @kevinbuhmann What is required to get this merged & released?

I will get this merged today.

**Comment by twittwer** [comment]
Can you say when the next release will be published?  
This is currently blocking our update.  
Or is there some next/beta tag to install clarity with the fix?

**Comment by twittwer** [comment]
@kevinbuhmann Can you estimate a time for next release with this fix?

**Pull request merged**
