### PR TITLE
feat: add support for Angular 18

### PR DESCRIPTION
**Pull request by repolevedavaj**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

There is no Angular 18 support.

Issue Number: N/A

## What is the new behavior?

There is Angular 18 support.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
I took https://github.com/vmware-clarity/ng-clarity/pull/1094 as reference.

### CODE REVIEW

**Review by kevinbuhmann — APPROVED** [review]
Thanks!

**Comment by repolevedavaj** [comment]
> Thanks!

No worries! I pushed again as they removed a test method in Angular 18, so i replaced it with the successor (already existed in Angular 15).

**Comment by kevinbuhmann** [comment]
Okay, the build has passed now. I will merge this as soon as the CLA is approved by legal.

**Comment by repolevedavaj** [comment]
@kevinbuhmann have you already planned the next release date?

**Comment by repolevedavaj** [comment]
Any update related to the CLA?

**Comment by kevinbuhmann** [comment]
Sorry, I have no visibility in the CLA process. The bot should post when it's approved. I also don't know when we will do our next feature release. We are focused on some needed bug fixes at the moment.

**Comment by repolevedavaj** [comment]
@kevinbuhmann Thank you for your feedback :)

**Comment by kumart-netapp** [comment]
Any update on this PR merge?

**Comment by kevinbuhmann** [comment]
@repolevedavaj Could you check the box to allow maintainers to update this branch? That will allow me to merge `main` into this PR so that we can merge.

**Comment by repolevedavaj** [comment]
@kevinbuhmann i think this option does not exist when creating fork in org accounts. Anyway i did the merge, so just let me know if you need anything else. Feel free to reopen a new pr with my changes if thats easier. Its not that much work anyway ;)

**Comment by kevinbuhmann** [comment]
I'm trying to follow up internally with the CLA. I'm not sure what happened with that yet.

**Comment by dangrussell** [comment]
Do you know yet when the next release including this code is expected to be available?

I'm assuming it will happen in the 18.x release of the `@clr/angular` package, but I don't know if there's a known release schedule or cycle.

(Sorry to press -- this is the last package in our stack that we're wait for to move to Angular 18.)

**Pull request merged**
