### PR TITLE
chore(accordion): extract stepper component styles in separate file

### PR DESCRIPTION
**Pull request by mivaylo**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: CDE-1476

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

For better organization of stepper and accordion components we want to split their styles

### CODE REVIEW

**Comment by williamernest** [comment]
I know this isn't out for review yet, but I just wanted to comment that this type of change is not a chore. The output of the SCSS stylesheet will be a different, so it could potentially affect how the CSS renders or the amount of specificity required to override a style rule. Since it could affect the components, it should be submitted as a fix or feature.

**Review by williamernest — CHANGES_REQUESTED** [review]
Discussed offline regarding the increase in specificity from nesting some of the CSS classes.

**Comment by kevinbuhmann** [comment]
I don't think CDE-1117 is the correct issue number for this.

**Comment by mivaylo** [comment]
> I don't think CDE-1117 is the correct issue number for this.

Thanks, fixed

**Review by kevinbuhmann — APPROVED** [review]

**Review by williamernest — APPROVED** [review]

**Pull request merged**
