### PR TITLE
fix(combobox): resolve `ComboboxFocusHandler` memory leaks and allow combobox to be garbage collected

### PR DESCRIPTION
**Pull request by arturovt**

### CODE REVIEW

**Review by mathisscott — APPROVED** [review]
Thanks, @arturovt 

I appreciate the comments you've added as well as the variable names you have used. It made it a lot easier to understand what problems this PR was solving.

**Comment by steve-haar** [comment]
GitHub failed to report workflow actions for this PR. Closing and reopening to trigger workflow.

**Review by Jinnie — CHANGES_REQUESTED** [review]
Looks good as code, but I am observing some problems when playing with the demo app.
Focus updates get lost when moving focus with arrow keys near the beginning or end of the dropdown list. I suppose that the scroll event in the other cases triggers re-rendering, while start/final items don't trigger scroll.
I need to verify if these problems are related to this issue or not, before being able to approve the PR.
There is also an Edge browser specific case I want to test, as I see we had some extra handling for the Edge browser in a code block that was removed.

**Comment by Jinnie** [comment]
I confirm that it looks in the main code line. Additionally, the static demos (first 2 in every section) are lacking focus handling whatsoever.
I'd be happy if we fix these problems and get the changes merged. If I have some spare cycles, I'll try to look at the code too. Also, @arturovt, if you need help with reproducing the problems or using the demo-app, please write back.

**Comment by Jinnie** [comment]
Closing, as due to internal refocusing we can't afford to spend much time on these optimizations.
Thanks a lot for your effort, we may come back to these PRs in future iterations.

**Pull request closed without merging**
