### PR TITLE
feat: refactor `ClrCommonStrings` interface to get rid of optional fields

### PR DESCRIPTION
**Pull request by mivaylo**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: CDE-49

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

BREAKING CHANGE: Some properties are removed from the `ClrCommonStrings` interface, and some are now required.

### CODE REVIEW

**Review by dtsanevmw — APPROVED** [review]

**Review by dtsanevmw — CHANGES_REQUESTED** [review]
Do a public-api update to update clarity-api.md

**Review by dtsanevmw — DISMISSED** [review]

**Comment by mivaylo** [comment]
CDE-49

**Comment by mivaylo** [comment]
> Isn't this a breaking change for users since they're no longer optional? We should hold off on landing this until we create our v16 branch and land it there if it is.

@williamernest  yes, it is a breaking change, not merging yet, should I put some other label to the PR, or do we need some other title in this case?

**Comment by williamernest** [comment]
> > Isn't this a breaking change for users since they're no longer optional? We should hold off on landing this until we create our v16 branch and land it there if it is.
> 
> @williamernest yes, it is a breaking change, not merging yet, should I put some other label to the PR, or do we need some other title in this case?

Adding "BREAKING CHANGE: [description]" into the PR description will ensure our semantic library picks it up as a breaking change. Changing the PR title to `fix` will ensure it appears in our changelog. Outside of that, we can wait until v16 is created (which should be soon).

**Comment by kevinbuhmann** [comment]
I went ahead and made the title/summary changes.

**Pull request merged**
